//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum temperature_controlled {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum hazmat {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum export {
    
    /// <remarks/>
    Y,
    
    /// <remarks/>
    N,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum status {
    
    /// <remarks/>
    N,
    
    /// <remarks/>
    R,
    
    /// <remarks/>
    F,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum payment_method {
    
    /// <remarks/>
    PP,
    
    /// <remarks/>
    CC,
    
    /// <remarks/>
    PC,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum transport_method {
    /// <remarks/>
    M,
    /// <remarks/>
    U,
    /// FD 09/26/2017   Per Jonny Ok to expand list to include Pick Ups ("H") as a valid trans method
    H,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum weight_unit_of_measure {
    
    /// <remarks/>
    LB,
    
    /// <remarks/>
    OZ,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum volume_unit_of_measure {
    
    /// <remarks/>
    CF,
    
    /// <remarks/>
    CM,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public enum type {
    
    /// <remarks/>
    SHIPFROM,
    
    /// <remarks/>
    SHIPTO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class reference {
    
    private string qualifierField;
    
    private string numberField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string qualifier {
        get {
            return this.qualifierField;
        }
        set {
            this.qualifierField = value;
        }
    }
    
    /// <remarks/>
    public string number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quorumresources.com")]
public partial class address_type {
    
    private type typeField;
    
    private string nameField;
    
    private string address1Field;
    
    private string address2Field;
    
    private string cityField;
    
    private string state_provinceField;
    
    private string postal_codeField;
    
    /// <remarks/>
    public type type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string address1 {
        get {
            return this.address1Field;
        }
        set {
            this.address1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string address2 {
        get {
            return this.address2Field;
        }
        set {
            this.address2Field = value;
        }
    }
    
    /// <remarks/>
    public string city {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    public string state_province {
        get {
            return this.state_provinceField;
        }
        set {
            this.state_provinceField = value;
        }
    }
    
    /// <remarks/>
    public string postal_code {
        get {
            return this.postal_codeField;
        }
        set {
            this.postal_codeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.quorumresources.com")]
public partial class detail_type {
    
    private string line_numberField;
    
    private string product_number_or_nmfcField;
    
    private string quantityField;
    
    private string lot_numberField;
    
    private reference referenceField;
    
    private decimal detail_cubeField;
    
    private bool detail_cubeFieldSpecified;
    
    private decimal detail_weightField;
    
    private bool detail_weightFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string line_number {
        get {
            return this.line_numberField;
        }
        set {
            this.line_numberField = value;
        }
    }
    
    /// <remarks/>
    public string product_number_or_nmfc {
        get {
            return this.product_number_or_nmfcField;
        }
        set {
            this.product_number_or_nmfcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    public string lot_number {
        get {
            return this.lot_numberField;
        }
        set {
            this.lot_numberField = value;
        }
    }
    
    /// <remarks/>
    public reference reference {
        get {
            return this.referenceField;
        }
        set {
            this.referenceField = value;
        }
    }
    
    /// <remarks/>
    public decimal detail_cube {
        get {
            return this.detail_cubeField;
        }
        set {
            this.detail_cubeField = value;
        }
    }
    
    ///// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool detail_cubeSpecified
    {
        get
        {
            return this.detail_cubeFieldSpecified;
        }
        set
        {
            this.detail_cubeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal detail_weight {
        get {
            return this.detail_weightField;
        }
        set {
            this.detail_weightField = value;
        }
    }
    
    ///// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool detail_weightSpecified
    {
        get
        {
            return this.detail_weightFieldSpecified;
        }
        set
        {
            this.detail_weightFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class header_reference {
    
    private string qualifierField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string qualifier {
        get {
            return this.qualifierField;
        }
        set {
            this.qualifierField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class note {
    
    private string qualifierField;
    
    private string descriptionField;
    
    /// <remarks/>
    public string qualifier {
        get {
            return this.qualifierField;
        }
        set {
            this.qualifierField = value;
        }
    }
    
    /// <remarks/>
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class total_weight {
    
    private decimal weightField;
    
    private weight_unit_of_measure weight_unit_of_measureField;
    
    /// <remarks/>
    public decimal weight {
        get {
            return this.weightField;
        }
        set {
            this.weightField = value;
        }
    }
    
    /// <remarks/>
    public weight_unit_of_measure weight_unit_of_measure {
        get {
            return this.weight_unit_of_measureField;
        }
        set {
            this.weight_unit_of_measureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class total_volume {
    
    private decimal volumeField;
    
    private volume_unit_of_measure volume_unit_of_measureField;
    
    /// <remarks/>
    public decimal volume {
        get {
            return this.volumeField;
        }
        set {
            this.volumeField = value;
        }
    }
    
    /// <remarks/>
    public volume_unit_of_measure volume_unit_of_measure {
        get {
            return this.volume_unit_of_measureField;
        }
        set {
            this.volume_unit_of_measureField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class asn {
    
    private string idField;
    
    private string luField;
    
    private string mrField;
    
    private string dpField;
    
    /// <remarks/>
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string lu {
        get {
            return this.luField;
        }
        set {
            this.luField = value;
        }
    }
    
    /// <remarks/>
    public string mr {
        get {
            return this.mrField;
        }
        set {
            this.mrField = value;
        }
    }
    
    /// <remarks/>
    public string dp {
        get {
            return this.dpField;
        }
        set {
            this.dpField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class order_detail {
    
    private detail_type[] detailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("detail")]
    public detail_type[] detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.quorumresources.com", IsNullable=false)]
public partial class warehouse_shipping_orders {
    
    private warehouse_shipping_ordersWarehouse_shipping_order[] warehouse_shipping_orderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("warehouse_shipping_order")]
    public warehouse_shipping_ordersWarehouse_shipping_order[] warehouse_shipping_order {
        get {
            return this.warehouse_shipping_orderField;
        }
        set {
            this.warehouse_shipping_orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.quorumresources.com")]
public partial class warehouse_shipping_ordersWarehouse_shipping_order {
    
    private string account_idField;
    
    private string account_numberField;
    
    private status statusField;
    
    private string customer_reference_numberField;
    
    private string consignee_poField;
    
    private export exportField;
    
    private temperature_controlled temperature_controlledField;
    
    private hazmat hazmatField;
    
    private payment_method payment_methodField;
    
    private transport_method transport_methodField;
    
    private string scacField;
    
    private total_weight total_weightField;
    
    private total_volume total_volumeField;
    
    private header_reference[] header_referenceField;
    
    private note[] noteField;
    
    private string shipment_dateField;
    
    private string delivery_dateField;
    
    private address_type[] addressField;
    
    private asn asnField;
    
    private string ucc128Field;
    
    private detail_type[] order_detailField;
    
    /// <remarks/>
    public string account_id {
        get {
            return this.account_idField;
        }
        set {
            this.account_idField = value;
        }
    }
    
    /// <remarks/>
    public string account_number {
        get {
            return this.account_numberField;
        }
        set {
            this.account_numberField = value;
        }
    }
    
    /// <remarks/>
    public status status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string customer_reference_number {
        get {
            return this.customer_reference_numberField;
        }
        set {
            this.customer_reference_numberField = value;
        }
    }
    
    /// <remarks/>
    public string consignee_po {
        get {
            return this.consignee_poField;
        }
        set {
            this.consignee_poField = value;
        }
    }
    
    /// <remarks/>
    public export export {
        get {
            return this.exportField;
        }
        set {
            this.exportField = value;
        }
    }
    
    /// <remarks/>
    public temperature_controlled temperature_controlled {
        get {
            return this.temperature_controlledField;
        }
        set {
            this.temperature_controlledField = value;
        }
    }
    
    /// <remarks/>
    public hazmat hazmat {
        get {
            return this.hazmatField;
        }
        set {
            this.hazmatField = value;
        }
    }
    
    /// <remarks/>
    public payment_method payment_method {
        get {
            return this.payment_methodField;
        }
        set {
            this.payment_methodField = value;
        }
    }
    
    /// <remarks/>
    public transport_method transport_method {
        get {
            return this.transport_methodField;
        }
        set {
            this.transport_methodField = value;
        }
    }
    
    /// <remarks/>
    public string scac {
        get {
            return this.scacField;
        }
        set {
            this.scacField = value;
        }
    }
    
    /// <remarks/>
    public total_weight total_weight {
        get {
            return this.total_weightField;
        }
        set {
            this.total_weightField = value;
        }
    }
    
    /// <remarks/>
    public total_volume total_volume {
        get {
            return this.total_volumeField;
        }
        set {
            this.total_volumeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("header_reference")]
    public header_reference[] header_reference {
        get {
            return this.header_referenceField;
        }
        set {
            this.header_referenceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("note")]
    public note[] note {
        get {
            return this.noteField;
        }
        set {
            this.noteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string shipment_date {
        get {
            return this.shipment_dateField;
        }
        set {
            this.shipment_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string delivery_date {
        get {
            return this.delivery_dateField;
        }
        set {
            this.delivery_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("address")]
    public address_type[] address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public asn asn {
        get {
            return this.asnField;
        }
        set {
            this.asnField = value;
        }
    }
    
    /// <remarks/>
    public string ucc128 {
        get {
            return this.ucc128Field;
        }
        set {
            this.ucc128Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("detail", IsNullable=false)]
    public detail_type[] order_detail {
        get {
            return this.order_detailField;
        }
        set {
            this.order_detailField = value;
        }
    }
}
